#Gems

gems: ['jekyll-polyglot']

# Site settings
title: BBox.co
email: hburbano@bbox.co
description:
  en: Site description
  es: Descripción del sitio
baseurl: ""
url: "http://bbox.co"

# Exclude from the generated _site

exclude: ["script", "Gemfile", "README", "LICENCE", "Rakefile","bbox.sublime-project", "vendor"]

#i18n Polyglot

languages: ["en", "es"]
default_lang: "en"
exclude_from_localization: ["js", "font-awesome", "fonts", "img", "css", "favicon.png"]
parallel_localization: true

# Config
twitter_username: nslaver
github_username: nslaver
keybase_username: nslaver

# Build settings
markdown: kramdown
