en:
  title: "What we offer!"
  list:
    agile:
      glyph: fa-plane
      title: "Agile"
      description: "Agile development in synchrony to changing needs."
    code:
      glyph: fa-code
      title: "Programming"
      description: "Full stack development in many flavors."
    multiplatform:
      glyph: fa-mobile
      title: "Multiplatform"
      description: "Agile development in syncroni to changing needs."
    cloud:
      glyph: fa-cloud
      title: "Cloud services"
      description: "Configuration and deployment to your favorite cloud provider."

es:
  title: "Que ofrecemos!"
  list:
    agile:
      glyph: fa-plane
      title: "Agil"
      description: "Desarrollo ágil en sincronía con necesidades cambiantes."
    code:
      glyph: fa-code
      title: "Desarrollo Full Stack"
      description: "Desarrollo Full Stack en diversos sabores."
    multiplatform:
      glyph: fa-mobile
      title: "Multiplataforma"
      description: "Desarrollo multiplataforma para tu publico especifico."
    cloud:
      glyph: fa-cloud
      title: "Cloud services"
      description: "Configuración y desarrollo a tu lugar favorito en la nube."